### ISSUE TITLE
Failed to start child `Elixir.Logger.Watcher`

### ISSUE THREAD

**Issue by Trevoke** [onkel-dirtus/logger_file_backend#38]
I think this is similar to #8 but ..

I'm using distillery, and I can't fix it the same way because.. I put `logger_file_backend` at the umbrella app level.

**Comment by xadhoom** [comment]
you may try putting it inside the apps/*/mix.exs as a dep.
and also check distillery schema for logger backend because by default it does not returns the tuple needed.
I had to remove, like done here: https://github.com/xadhoom/detectino-core/commit/e7b1f2c60ca7c3ebdfa1bb36ed67f80a0be9b524 and then it worked

(I think you can also fix it by using distillery transforms, but well, in my case I don't need to configure backends at runtime)
